<?php
/**
 * CanvassContext
 *
 * PHP version 5
 *
 * @category Class
 * @package  NGP
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Coding as activism
 *
 * TODO: Add Description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace NGP\Model;

use \ArrayAccess;
use \NGP\ObjectSerializer;

/**
 * CanvassContext Class Doc Comment
 *
 * @category Class
 * @package  NGP
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CanvassContext implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'CanvassContext';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'contact_type_id' => 'int',
        'date_canvassed' => 'string',
        'input_type_id' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'contact_type_id' => 'int32',
        'date_canvassed' => null,
        'input_type_id' => 'int32'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'contact_type_id' => 'contactTypeId',
        'date_canvassed' => 'dateCanvassed',
        'input_type_id' => 'inputTypeId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'contact_type_id' => 'setContactTypeId',
        'date_canvassed' => 'setDateCanvassed',
        'input_type_id' => 'setInputTypeId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'contact_type_id' => 'getContactTypeId',
        'date_canvassed' => 'getDateCanvassed',
        'input_type_id' => 'getInputTypeId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['contact_type_id'] = isset($data['contact_type_id']) ? $data['contact_type_id'] : null;
        $this->container['date_canvassed'] = isset($data['date_canvassed']) ? $data['date_canvassed'] : null;
        $this->container['input_type_id'] = isset($data['input_type_id']) ? $data['input_type_id'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['contact_type_id'] === null) {
            $invalidProperties[] = "'contact_type_id' can't be null";
        }
        if ($this->container['date_canvassed'] === null) {
            $invalidProperties[] = "'date_canvassed' can't be null";
        }
        if ($this->container['input_type_id'] === null) {
            $invalidProperties[] = "'input_type_id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets contact_type_id
     *
     * @return int
     */
    public function getContactTypeId()
    {
        return $this->container['contact_type_id'];
    }

    /**
     * Sets contact_type_id
     *
     * @param int $contact_type_id contact_type_id
     *
     * @return $this
     */
    public function setContactTypeId($contact_type_id)
    {
        $this->container['contact_type_id'] = $contact_type_id;

        return $this;
    }

    /**
     * Gets date_canvassed
     *
     * @return string
     */
    public function getDateCanvassed()
    {
        return $this->container['date_canvassed'];
    }

    /**
     * Sets date_canvassed
     *
     * @param string $date_canvassed date_canvassed
     *
     * @return $this
     */
    public function setDateCanvassed($date_canvassed)
    {
        $this->container['date_canvassed'] = $date_canvassed;

        return $this;
    }

    /**
     * Gets input_type_id
     *
     * @return int
     */
    public function getInputTypeId()
    {
        return $this->container['input_type_id'];
    }

    /**
     * Sets input_type_id
     *
     * @param int $input_type_id input_type_id
     *
     * @return $this
     */
    public function setInputTypeId($input_type_id)
    {
        $this->container['input_type_id'] = $input_type_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


