<?php
/**
 * MiscApiTest
 * PHP version 5
 *
 * @category Class
 * @package  NGP
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Coding as activism
 *
 * TODO: Add Description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace NGP;

use \NGP\Configuration;
use \NGP\ApiException;
use \NGP\ObjectSerializer;

/**
 * MiscApiTest Class Doc Comment
 *
 * @category Class
 * @package  NGP
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MiscApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for echoesPost
     *
     * Hello world.
     *
     */
    public function testEchoesPost()
    {
    }

    /**
     * Test case for events4306Get
     *
     * Get event details.
     *
     */
    public function testEvents4306Get()
    {
    }

    /**
     * Test case for people100879417CanvassResponsesPost
     *
     * Collect canvass data.
     *
     */
    public function testPeople100879417CanvassResponsesPost()
    {
    }

    /**
     * Test case for peopleFindOrCreatePost
     *
     * Create a volunteer record.
     *
     */
    public function testPeopleFindOrCreatePost()
    {
    }

    /**
     * Test case for signupsPost
     *
     * RSVP to an event.
     *
     */
    public function testSignupsPost()
    {
    }
}
